version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: portfolio-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: samuel-portfolio

  server:
    build: ./server
    container_name: portfolio-server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/samuel-portfolio
      - JWT_SECRET=your-secret-key-here
      - NODE_ENV=production
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build: ./client
    container_name: portfolio-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000

volumes:
  mongodb_data: